#!/usr/bin/env python3
"""Generate placeholder .glb meshes for demo/fallback mode.

Creates simple geometric garment-like shapes using trimesh.
These are temporary until real meshes are generated by the ML pipeline.

Usage: python scripts/generate_samples.py
"""

import sys
from pathlib import Path

# Add backend to path for mesh_utils
sys.path.insert(0, str(Path(__file__).parent.parent / "backend"))

from mesh_utils import create_placeholder_glb

FRONTEND_MESHES = Path(__file__).parent.parent / "frontend" / "public" / "sample-meshes"

SHAPES = ["tshirt", "skirt", "pants", "dress"]


def main():
    FRONTEND_MESHES.mkdir(parents=True, exist_ok=True)

    for shape in SHAPES:
        out = FRONTEND_MESHES / f"{shape}.glb"
        create_placeholder_glb(out, shape=shape)
        print(f"  Created {out} ({out.stat().st_size / 1024:.1f} KB)")

    print(f"\nGenerated {len(SHAPES)} sample meshes in {FRONTEND_MESHES}")


if __name__ == "__main__":
    main()
